version: '3'
services:
  flask-app:
    build:
      context: ./
      dockerfile: dockerfiles/python
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./configfiles/flask.conf:/etc/nginx/conf.d/flask.conf
    ports:
      - "80:80"
    networks:
      - default

networks:
  default:
    external:
      name: nebulosa-dev
